### ISSUE TITLE
Passing Data to Vue

### ISSUE THREAD

**Issue by Jafesu** [alenvalek/fivem-vuejs-boilerplate#1]
I am trying to pass a table to my VUE app and for whatever reason, the table is showing as null in the vue app

Not sure if i am just doing something dump... but if you could look at it and advise i would be greatful

Client.lua function
```
function SendPlayerDataToApp()
   local playerID = PlayerPedId()
   -- print(playerID)
   local PlayerID = GetPlayerServerId(NetworkGetPlayerIndexFromPed(playerID))
   -- print(PlayerID)
   ESX.TriggerServerCallback('ejcscomp:getPlayerData', function(playerData)
      job = ESX.GetPlayerData().job.name
      grade = ESX.GetPlayerData().job.grade
      playerData.job.name = job
      playerData.job.grade = grade
      -- print(playerData.name)
      -- print(job)
      print(label)
      SendNUIMessage({
         type = 'setPlayerData',
         data = playerData
      })
   end,PlayerID)
   
```

Server.lua function

```
ESX.RegisterServerCallback('ejcscomp:getPlayerData', function(source, cb, PlayerID)
        print(PlayerID)
        local playerData = {}
        local xPlayer = ESX.GetPlayerFromId(PlayerID)
        -- print(xPlayer)
        playerData.id = PlayerID
        playerData.name = xPlayer.name
        playerData.job = {}
        cb(playerData)
    end)
```

Store
```
export default new Vuex.Store({
	state: {
		playerData: {},
	},
	getters: {
		playerData(state) {
			return state.playerData;
		},
	},
	mutations: {
		setplayerData(state, payload) {
			print("Player Data:")
			print(payload.data)
			state.playerData = payload.data;
		},
	},
	actions: {},
});
```

mapGetters
```
computed: {
		...mapGetters(["playerData"]),
	},
```

display
```
<div v-if="playerData">
					<div>PlayerID: {{ playerData.id}}</div>
					<div>PlayerName: {{ playerData.name}}</div>
					<div>Job: {{ playerData.job.name}}</div>
					<div>Rank: {{ playerData.job.rank}}</div>
				</div>
```

**Comment by Jafesu** [comment]
If i put just `{{playerData}}` in my div i get an empty object
![image](https://user-images.githubusercontent.com/22550683/187606052-2ea0e87c-ec55-4db6-a6aa-264a24f419fd.png)

**Comment by alenvalek** [comment]
Hey, I believe you're supposed to turn the table into json first. Let me know if that works for you.

**Comment by Jafesu** [comment]
Can i convert to JSON in LUA?

**Comment by alenvalek** [comment]
> Can i convert to JSON in LUA?

Yes, you can find a module or build your own function

**Comment by Jafesu** [comment]
Looks like FiveM has a native json.encode that i am trying to use ( https://github.com/citizenfx/fivem/blob/master/data/shared/citizen/scripting/lua/json.lua) 

When i print(type()) on the var after converting to json, it prints as string which makes sense
then i JSON.parse() it in my store, and it is still empty. 
even if i dont parse it and just let it pass through as a string its coming up empty

update:
client.lua
`ESX.TriggerServerCallback('ejcscomp:getPlayerData', function(playerData)
      job = ESX.GetPlayerData().job.name
      grade = ESX.GetPlayerData().job.grade
      label = ESX.GetPlayerData().job.grade_label
      rank = ESX.GetPlayerData().job.grade_name
      playerData.job.name = job
      playerData.job.grade = grade
      print(label)
      print(rank)
      playerData = json.encode(playerData)
      print(type(playerData))
      -- print(playerData.name)
      -- print(job)
      
      SendNUIMessage({
         type = 'setPlayerData',
         data = playerData
      })
   end,PlayerID)`

vuexstore
`export default new Vuex.Store({
	state: {
		playerData: {},
	},
	getters: {
		playerData(state) {
			return state.playerData;
		},
	},
	mutations: {
		setplayerData(state, payload) {
			state.playerData = JSON.parse(payload.data);
		},
	},
	actions: {},
});`

If you want to look at my full code it is here: https://github.com/EzekielJConsulting/EJCS_Computers/tree/EJCSCOMP-2-ComputerUI

I really appreciate all the help
