### ISSUE TITLE
Error running Build

### ISSUE THREAD

**Issue by Adzeiros** [alenvalek/fivem-vuejs-boilerplate#4]
I get an error when trying to run the "npm run build" command.

It throws this error: "Error: Debug Failure. False expression: Paths must either both be absolute or both be relative"

**Comment by DanzoDev** [comment]
same here, didnt find a fix so far

**Comment by alenvalek** [comment]
Hi @DanzoDev, @Adzeiros this is a bug with typescript compiler. Problem has been reported on official repo 2 weeks ago. For the moment I have lowered ts version to 4.9.2. Can you guys please test if this fixed the issue and let me know.

Thx for the report!

**Comment by Adzeiros** [comment]
> Hi @DanzoDev, @Adzeiros this is a bug with typescript compiler. Problem has been reported on official repo 2 weeks ago. For the moment I have lowered ts version to 4.9.2. Can you guys please test if this fixed the issue and let me know.
> 
> Thx for the report!

So, I lowered the version to the one mentioned. It does state it builds now but it doesn't produce a "dist" folder. It also throws an error saying the import "/src/main.ts" cannot be resolved.

**Comment by alenvalek** [comment]
This is what I'm currently getting
![image](https://github.com/alenvalek/fivem-vuejs-boilerplate/assets/60185462/99107099-3e02-4109-abba-434f5f318cd3)
My builds pass and everything works as expected. Can you please try removing tsconfig.tsbuildinfo file and reinstalling dependenices by removing node modules folder?

**Comment by Adzeiros** [comment]
@alenvalek So I deleted the node modules folder, and deleted the tsconfig.tsbuildinfo file. However, when I ran the npm install and then ran "npm run build" I get the below error:

![image](https://github.com/alenvalek/fivem-vuejs-boilerplate/assets/87957267/fc4bab6f-393b-4d61-8136-24b6a425b01c)

**Comment by alenvalek** [comment]
After a lot of testing on different devices, my builds keep passing without a problem. Can someone with this issue please provide the following details:
- OS
- npm version
- node version
@Adzeiros @fatalcobra22

**Comment by Adzeiros** [comment]
@alenvalek 

My node version: v21.6.1
OS: Windows 11 V. 22H2
NPM Version: 10.2.4

On a fresh clone, I get the same error as the one I posted above.

**Comment by alenvalek** [comment]
Hello once again @Adzeiros, @fatalcobra22, @DanzoDev.. After taking another look at this issue I still cannot reproduce this behavior with identical settings to yours. I have however managed to force the appearance of the error.
![image](https://github.com/alenvalek/fivem-vuejs-boilerplate/assets/60185462/5eec6c01-5b2c-489b-998a-db3f806fb1f7)
When any of you get the time could you please try to experiment with the following line:
 ```<script type="module" src="/src/main.ts"></script>```
 
 - Try replacing *"/src/main.ts"* with *"@/main.ts"*

**Comment by alenvalek** [comment]
Systems where I tried to replicate the issue:
- Ubuntu 22.04.4
- Fedora Workstation 39
- Windows 11 23H2

As for node/npm I always use the versions provided:
- node v21.6.1
- npm v10.2.4

**Comment by alenvalek** [comment]
which terminal are you using? @Adzeiros

**Comment by Adzeiros** [comment]
@alenvalek I have tried from Powershell as well as CMD...

**Comment by alenvalek** [comment]
I've opened a branch to resolve this issue, [issue-build branch](https://github.com/alenvalek/fivem-vuejs-boilerplate/tree/issue-build), currently the branch is in the state before the TS downgrade
