### ISSUE TITLE
How do see UI on http://localhost:3000/ when developing UI?

### ISSUE THREAD

**Issue by akshaynstack** [alenvalek/fivem-vuejs-boilerplate#9]
How do see UI on http://localhost:3000/ when developing UI?

I tried npm run dev but I am seeing blank white screen

**Comment by alenvalek** [comment]
Hi @akshaynstack, to develop within your browser you need to change ref value of isVisible to "true" inside App.vue file. Let me know if this helps!

```ts
const isVisible = ref(true);
```

**Comment by akshaynstack** [comment]
Thanks
